services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=flowchart-api-db
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=admin
    
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    
    ports:
      - 27017-27019:27017-27019

  api:
    image: flowchart-api
    restart: always
    environment:
      - DB_URI=mongodb://admin:admin@db:27017/flowchart-api-db

    ports:
      - 3000:3000

    links:
      - db
